"""update employee schema and add department position tables

Revision ID: a4362f10e647
Revises: 4deb101c2dfc
Create Date: 2025-01-13 17:11:43.732744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a4362f10e647'
down_revision: Union[str, None] = '4deb101c2dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_code', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_department_code'), 'departments', ['department_code'], unique=True)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_code', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_position_code'), 'positions', ['position_code'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('salary', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('contract_id', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_place', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('id_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', name='maritalstatus'), nullable=False),
    sa.Column('ethnicity', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('education_level_id', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('id_card_date', sa.Date(), nullable=True),
    sa.Column('id_card_place', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('health_insurance_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('social_insurance_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('profile_image_path', mysql.VARCHAR(length=40), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('EmployeeID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=False),
    sa.Column('PositionID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True),
    sa.Column('DepartmentID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True),
    sa.Column('Salary', mysql.FLOAT(), nullable=False),
    sa.Column('Gender', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4), nullable=True),
    sa.Column('ContractID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True),
    sa.Column('EmployeeName', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('DateOfBirth', sa.DATE(), nullable=False),
    sa.Column('PlaceOfBirth', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('IDNumber', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('Phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('Address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('Email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('MaritalStatus', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('Ethnicity', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('EducationLevelID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True),
    sa.Column('IDCardDate', sa.DATE(), nullable=True),
    sa.Column('IDCardPlace', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('HealthInsurance', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('SocialInsurance', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('ID_profile_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=True),
    sa.PrimaryKeyConstraint('EmployeeID'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_positions_position_code'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_departments_department_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
