"""Fix payroll datetime fields

Revision ID: a6918f64152c
Revises: 0e56ddd40d15
Create Date: 2025-01-14 21:49:34.890342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6918f64152c'
down_revision: Union[str, None] = '0e56ddd40d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contracts', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payrolls', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payrolls', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payrolls', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('payrolls', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=mysql.DATETIME(),
               nullable=False)
    op.alter_column('contracts', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('contracts', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
